task adn emp data refinement so that we can pull more from localStorage
fluviangumbo/Management-Calendar pull request #33
Opened 2024-07-22 19:51 UTC by fluviangumbo

added more employee data, can now find employees by index
added task data, can now use this to visually order tasks and look up info on them
will still need a way to connect them and render

2024-07-22 21:35 UTC, bungin requested changes
![image](https://github.com/user-attachments/assets/43b4276c-12b7-4cfb-bf7c-5f5a7677c34f)
cant submit numbers as instructed.

![image](https://github.com/user-attachments/assets/dfee641a-a7f7-44b0-b517-c42c78092378)

on submit nothing is saved as expected(error message). also spelling of "please"

2024-07-22 21:39 UTC, bungin commented on assets/js/script.js
> +  } else if (!(typeof taskStartInp === 'number') || !(typeof taskDurationInp === 'number')) {
i think the "!" should be inside the parentheticals, could be wrong.

2024-07-22 22:26 UTC, fluviangumbo reviewed
changes made

2024-07-23 00:00 UTC, bungin approved these changes

2024-07-23 00:00 UTC, merged